defaults: grpo-qwen3.5-35ba3b-6n4g-async-1off-mxfp8-moe-trtllm.yaml

checkpointing:
  checkpoint_dir: results/grpo-nemotron3.5-lightning-30ba3b-6n4g-async-1off-mxfp8-moe-trtllm

policy:
  model_name: nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16
  megatron_cfg:
    bias_activation_fusion: false
    moe_router_dtype: fp32
  generation:
    vllm_cfg:
      quantization_ignore_patterns:
        - "*layers.*.mixer.qkv_proj"
        - "*layers.*.mixer.o_proj"
        - "*layers.*.mixer.in_proj"
        - "*layers.*.mixer.out_proj"
        - "*layers.*.mixer.up_proj"
        - "*layers.*.mixer.down_proj"
        - "*layers.*.mixer.gate"
        - "*layers.*.mixer.shared_experts.*"
        - "*layers.*.mixer.fc1_latent_proj"
        - "*layers.*.mixer.fc2_latent_proj"
        - "*mtp.*"
        - lm_head

logger:
  wandb:
    project: nemo-rl-pr3659-mixed-refit
    name: nemotron3.5-lightning-async-mxfp8-moe-first2-last6
