defaults: grpo-qwen3.5-9b-1n8g-megatron.yaml
grpo:
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-qwen3.8-27b-2n8g-megatron-tp4pp2cp2
policy:
  model_name: Qwen/Qwen3.8-27B
  train_global_batch_size: 256
  sequence_packing:
    enabled: true
  make_sequence_length_divisible_by: 16
  megatron_cfg:
    pipeline_model_parallel_size: 2
    context_parallel_size: 2
logger:
  wandb:
    name: grpo-qwen3.8-27b-2n8g-megatron-tp4pp2cp2
cluster:
  num_nodes: 2
