defaults: ./grpo-qwen2.5-math-1.5b-instruct-1n8g-megatron_generation-noncolocated-single-controller-async-lag4.yaml
logger:
  log_dir: logs/grpo-qwen2.5-math-1.5b-instruct-1n8g-megatron_generation-single-controller-async-lag4
  wandb:
    name: grpo-qwen2.5-math-1.5b-instruct-1n8g-megatron_generation-single-controller-async-lag4
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-math-1.5b-instruct-1n8g-megatron_generation-single-controller-async-lag4
policy:
  generation:
    colocated:
      enabled: true
      resources:
        gpus_per_node: null
        num_nodes: null
