defaults: ./grpo-llama3.1-8b-instruct-2n4g.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-8b-2n4g-specdec
policy:
  model_name: Qwen/Qwen3-8B
  tokenizer:
    name: Qwen/Qwen3-8B
  generation:
    stop_token_ids: null
    vllm_cfg:
      enforce_eager: false
    vllm_kwargs:
      speculative_config:
        method: ${oc.env:NRL_SPEC_METHOD,dflash}
        model: ${oc.env:NRL_DRAFT_MODEL,z-lab/Qwen3-8B-DFlash-b16}
        num_speculative_tokens: ${oc.decode:${oc.env:NRL_NUM_SPECULATIVE_TOKENS,7}}
        draft_tensor_parallel_size: 1
data:
  train:
    dataset_name: OpenMathInstruct-2
  default:
    processor: math_hf_data_processor
    env_name: math
env:
  math:
    math_verify_impl: hf_math_verify
logger:
  log_dir: logs/grpo-qwen3-8b-2n4g-specdec
  wandb:
    name: grpo-qwen3-8b-2n4g-specdec
cluster:
  gpus_per_node: 4
  num_nodes: 2
  segment_size: 2
