defaults: ./grpo-qwen3-8b-1n4g-nocg.yaml
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-8b-1n4g-nocg-short2048
policy:
  max_total_sequence_length: 2048
  generation:
    max_new_tokens: 2048
    vllm_cfg:
      max_model_len: 2048
  sequence_packing:
    enabled: true
    train_mb_tokens: 2048
    logprob_mb_tokens: 2048
    algorithm: modified_first_fit_decreasing
    sequence_length_round: 64
data:
  max_input_seq_length: 1024
logger:
  log_dir: logs/grpo-qwen3-8b-1n4g-nocg-short2048
  wandb_enabled: true
  tensorboard_enabled: false
  wandb:
    project: nemo-rl-cudagraph
    name: grpo-qwen3-8b-1n4g-nocg-short2048
