defaults: ../grpo-nanov3-30BA3B-2n8g-megatron-pack-cp.yaml
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-nanov3-30ba3b-8n4g-mxfp8-e2e-fp8param-false
loss_fn:
  use_importance_sampling_correction: true
policy:
  megatron_cfg:
    moe_router_dtype: fp32
    fp8_cfg:
      enabled: true
      fp8: e4m3
      fp8_recipe: mxfp8
      fp8_param: false
    te_precision_config_file: examples/nemo_gym/nemotron-3.5-nano/te_mxfp8_nano_v2.yaml
    first_last_layers_bf16: true
    num_layers_at_start_in_bf16: 0
    num_layers_at_end_in_bf16: 8
  generation:
    refit_transport: nccl_reshard
    colocated:
      enabled: false
      resources:
        num_nodes: 4
        gpus_per_node: 4
    vllm_cfg:
      tensor_parallel_size: 1
      gpu_memory_utilization: 0.5
      precision: fp8
      is_mx: true
      quantization_ignore_patterns:
      - model.layers.*.mixer.qkv_proj
      - model.layers.*.mixer.o_proj
      - model.layers.*.mixer.in_proj
      - model.layers.*.mixer.out_proj
      - model.layers.*.mixer.up_proj
      - model.layers.*.mixer.down_proj
      - model.layers.*.mixer.gate
      - model.layers.*.mixer.shared_experts.*
      - model.layers.*.mixer.fc1_latent_proj
      - model.layers.*.mixer.fc2_latent_proj
      - lm_head
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
logger:
  log_dir: logs/grpo-nanov3-30ba3b-8n4g-mxfp8-e2e-fp8param-false
  wandb:
    name: grpo-nanov3-30ba3b-8n4g-mxfp8-e2e-fp8param-false
cluster:
  gpus_per_node: 4
  num_nodes: 8
  segment_size: 4
