defaults: ./grpo-qwen3-235b-32n4g-async-1off.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-32n4g-async-1off-tp4
policy:
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
logger:
  log_dir: logs/grpo-qwen3-235b-32n4g-async-1off-tp4
  wandb:
    name: grpo-qwen3-235b-32n4g-async-1off-tp4
cluster:
  segment_size: 16
