defaults: ./grpo-qwen3-8b-1n4g-nocg-nopack.yaml
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-8b-1n4g-cg-mlp-w6-nopack
policy:
  megatron_cfg:
    cuda_graph_impl: transformer_engine
    cuda_graph_scope: mlp
    cuda_graph_warmup_steps: 6
    cuda_graph_packed_seq: false
    cuda_graph_buckets:
    - 4096
logger:
  log_dir: logs/grpo-qwen3-8b-1n4g-cg-mlp-w6-nopack
  wandb_enabled: false
  tensorboard_enabled: false
  wandb:
    name: grpo-qwen3-8b-1n4g-cg-mlp-w6-nopack
