defaults: ./grpo-nemotron3.5-lightning-30ba3b-4n4g-sync-mxfp8-qkvo-moe-rollout.yaml

checkpointing:
  checkpoint_dir: results/grpo-nemotron3.5-lightning-30ba3b-4n4g-sync-mxfp8-moe-control

policy:
  generation:
    vllm_cfg:
      quantization_ignore_patterns:
        - "*layers.*.mixer.qkv_proj"
        - "*layers.*.mixer.o_proj"
        - "*layers.*.mixer.in_proj"
        - "*layers.*.mixer.out_proj"
        - "*layers.*.mixer.up_proj"
        - "*layers.*.mixer.down_proj"
        - "*layers.*.mixer.gate"
        - "*layers.*.mixer.shared_experts.*"
        - "*layers.*.mixer.fc1_latent_proj"
        - "*layers.*.mixer.fc2_latent_proj"
        - "*mtp.*"
        - lm_head

logger:
  log_dir: logs/grpo-nemotron3.5-lightning-30ba3b-4n4g-sync-mxfp8-moe-control
  wandb:
    name: nemotron3.5-lightning-sync-mxfp8-moe-first1-last3-control
