defaults: ./grpo-nemotron3.5-lightning-30ba3b-8n4g-async-1off-mxfp8-qkvo-moe-rollout.yaml
grpo:
  async_grpo:
    enabled: false
    in_flight_weight_updates: false
checkpointing:
  checkpoint_dir: results/grpo-nemotron3.5-lightning-30ba3b-4n4g-sync-mxfp8-qkvo-moe-rollout
policy:
  generation:
    refit_transport: null
    colocated:
      enabled: true
      resources:
        gpus_per_node: null
        num_nodes: null
    vllm_cfg:
      async_engine: false
      refit_prequantize: true
      refit_cache_loader_routes: true
logger:
  log_dir: logs/grpo-nemotron3.5-lightning-30ba3b-4n4g-sync-mxfp8-qkvo-moe-rollout
  wandb:
    name: nemotron3.5-lightning-sync-mxfp8-qkvo-moe-first1-last3
cluster:
  num_nodes: 4
  segment_size: 4
