defaults: ./grpo-qwen3-30ba3b-1n4g-megatron-mxfp8-cutedsl.yaml
grpo:
  num_prompts_per_step: 8
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-2n4g-megatron-mxfp8-factorial
policy:
  train_global_batch_size: 16
  generation:
    vllm_cfg:
      env_vars:
        VLLM_USE_STANDALONE_COMPILE: "0"
  megatron_cfg:
    expert_model_parallel_size: 8
    cuda_graph_impl: none
    cuda_graph_warmup_steps: 3
    cuda_graph_use_single_mempool: true
logger:
  log_dir: logs/grpo-qwen3-30ba3b-2n4g-megatron-mxfp8-factorial
  wandb:
    name: grpo-qwen3-30ba3b-2n4g-megatron-mxfp8-factorial
cluster:
  num_nodes: 2
  segment_size: 2
