defaults: ../grpo-qwen3.5-35ba3b-6n4g-async-1off-bf16-trtllm.yaml

grpo:
  max_num_steps: 20

checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3.5-35ba3b-8n4g-async-1off-mxfp8-moe-rollout

policy:
  generation:
    colocated:
      resources:
        gpus_per_node: 4
        num_nodes: 4
    vllm_cfg:
      precision: fp8
      is_mx: true
      num_first_layers_in_bf16: 2
      num_last_layers_in_bf16: 6
      quantization_ignore_patterns:
        - "*layers.*.self_attn.*"
        - "*layers.*.linear_attn.*"
        - "*layers.*.mlp.gate"
        - "*layers.*.mlp.shared_experts.*"
        - "*visual.*"
        - "*mtp.*"
        - lm_head
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
      expert_placement_strategy: linear

logger:
  log_dir: logs/grpo-qwen3.5-35ba3b-8n4g-async-1off-mxfp8-moe-rollout
  wandb:
    project: nemo-rl-pr3659-mixed-refit
    name: qwen3.5-35ba3b-async-mxfp8-moe-first2-last6

cluster:
  gpus_per_node: 4
  num_nodes: 8
  segment_size: 2
