defaults: ./grpo-qwen3-235b-16n8g.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-235b-16n4g
policy:
  megatron_cfg:
    pipeline_model_parallel_size: 4
    num_layers_in_first_pipeline_stage: 23
    num_layers_in_last_pipeline_stage: 23
    env_vars:
      NUM_OF_HYBRID_EP_RANKS_PER_NVLINK_DOMAIN: '16'
      NVLINK_DOMAIN_SIZE: '72'
      USE_MNNVL: '1'
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:False
  generation:
    vllm_cfg:
      tensor_parallel_size: 4
      pipeline_parallel_size: 2
      gpu_memory_utilization: 0.72
    vllm_kwargs:
      moe_backend: flashinfer_trtllm
      distributed_timeout_seconds: 2400
      compilation_config:
        cudagraph_capture_sizes:
        - 1
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
logger:
  log_dir: logs/grpo-qwen3-235b-16n4g
  wandb:
    name: grpo-qwen3-235b-16n4g
cluster:
  gpus_per_node: 4
  segment_size: 16
