defaults: ./grpo-nanov3-30ba3b-8n4g-mxfp8-e2e-fp8param-false.yaml
checkpointing:
  checkpoint_dir: results/grpo-nanov3-30ba3b-8n4g-bf16-train-mxfp8-rollout
policy:
  megatron_cfg:
    fp8_cfg:
      enabled: false
    te_precision_config_file: null
    first_last_layers_bf16: false
    num_layers_at_start_in_bf16: 0
    num_layers_at_end_in_bf16: 0
logger:
  log_dir: logs/grpo-nanov3-30ba3b-8n4g-bf16-train-mxfp8-rollout
  wandb:
    name: grpo-nanov3-30ba3b-8n4g-bf16-train-mxfp8-rollout
