defaults: ./grpo-qwen3-30ba3b-4n4g-async-1off-mxfp8-rollout.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n4g-async-1off-mxfp8-e2e-fp8param-false
policy:
  megatron_cfg:
    fp8_cfg:
      enabled: true
      fp8_recipe: mxfp8
  generation:
    refit_transport: nccl_reshard
logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n4g-async-1off-mxfp8-e2e-fp8param-false
  wandb:
    name: grpo-qwen3-30ba3b-4n4g-async-1off-mxfp8-e2e-fp8param-false
