defaults: ./grpo-qwen3-8b-1n4g-cg-attn-mlp-w6-pack8192.yaml
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-8b-1n4g-cg-attn-mlp-w6-pack-cgpackoff
policy:
  megatron_cfg:
    cuda_graph_packed_seq: false
logger:
  log_dir: logs/grpo-qwen3-8b-1n4g-cg-attn-mlp-w6-pack-cgpackoff
  wandb_enabled: false
  tensorboard_enabled: false
  wandb:
    name: grpo-qwen3-8b-1n4g-cg-attn-mlp-w6-pack-cgpackoff
