defaults: ./grpo-qwen3-30ba3b-4n4g.yaml
grpo:
  max_num_steps: 20
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n4g-nocg
policy:
  sequence_packing:
    enabled: true
    train_mb_tokens: 4096
    logprob_mb_tokens: 4096
    algorithm: modified_first_fit_decreasing
    sequence_length_round: 64
logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n4g-nocg
  wandb_enabled: false
  tensorboard_enabled: false
  wandb:
    name: grpo-qwen3-30ba3b-4n4g-nocg
