defaults: ./grpo-qwen3-8b-1n4g-cg-attn-w6.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen3-8b-1n4g-cg-attn-w3
policy:
  megatron_cfg:
    cuda_graph_warmup_steps: 3
    cuda_graph_max_packed_seqs: 64
logger:
  log_dir: logs/grpo-qwen3-8b-1n4g-cg-attn-w3
  wandb_enabled: true
  tensorboard_enabled: false
  wandb:
    project: nemo-rl-cudagraph
    name: grpo-qwen3-8b-1n4g-cg-attn-w3
