defaults: ./grpo-qwen3-30ba3b-4n4g.yaml
grpo:
  max_num_steps: 20
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-30ba3b-4n4g-nocg-nopack
policy:
  sequence_packing:
    enabled: false
logger:
  log_dir: logs/grpo-qwen3-30ba3b-4n4g-nocg-nopack
  wandb_enabled: false
  tensorboard_enabled: false
  wandb:
    name: grpo-qwen3-30ba3b-4n4g-nocg-nopack
