defaults: ../grpo-nanov3-30BA3B-2n8g-megatron-pack-cp.yaml

checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-nanov3-30ba3b-8n4g-bf16-rollout-nccl

loss_fn:
  force_on_policy_ratio: false
  use_importance_sampling_correction: true

policy:
  precision: bfloat16
  train_global_batch_size: 16
  generation:
    refit_transport: nccl_reshard
    colocated:
      enabled: false
      resources:
        num_nodes: 4
        gpus_per_node: 4
    vllm_cfg:
      tensor_parallel_size: 1
      pipeline_parallel_size: 1
      expert_parallel_size: 1
      gpu_memory_utilization: 0.5
      async_engine: false
      precision: bfloat16
    vllm_kwargs:
      moe_backend: triton

logger:
  log_dir: logs/grpo-nanov3-30ba3b-8n4g-bf16-rollout-nccl
  wandb:
    project: nemo-rl
    name: grpo-nanov3-30ba3b-8n4g-bf16-rollout-nccl

cluster:
  gpus_per_node: 4
  num_nodes: 8
  segment_size: 4
