defaults: grpo_math_1B_megatron_single_controller.yaml
policy:
  generation:
    backend: megatron
    mcore_generation_config:
      cuda_graph_sizing_distribution: hybrid
      cuda_graph_max_tokens: 512
      prefix_caching_mamba_gb: null
      prefix_caching_eviction_policy: lru
      prefix_caching_coordinator_policy: longest_prefix
      prefix_cache_ttl_seconds: 300.0
      prefix_caching_routing_alpha: 1.0
      http_server_num_replicas: 8
    colocated:
      enabled: true
      resources:
        gpus_per_node: null
        num_nodes: null
